package ArduinoML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_OPERATOR extends EnumerationDescriptorBase {

  public EnumerationDescriptor_OPERATOR() {
    super(0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x4579a879d7243242L, "OPERATOR", "r:1e4e32fc-e42a-4b05-84e5-5f0ea797c86d(ArduinoML.structure)/5006217702052999746", PrimitiveTypeId.STRING);
  }

  private final EnumerationDescriptor.MemberDescriptor myMember__0 = new EnumerationDescriptor.MemberDescriptor("==", "equals", "r:1e4e32fc-e42a-4b05-84e5-5f0ea797c86d(ArduinoML.structure)/5006217702052999748", "equals");
  private final EnumerationDescriptor.MemberDescriptor myMember__1 = new EnumerationDescriptor.MemberDescriptor(">", "greater", "r:1e4e32fc-e42a-4b05-84e5-5f0ea797c86d(ArduinoML.structure)/5006217702052999747", "greater");
  private final EnumerationDescriptor.MemberDescriptor myMember__2 = new EnumerationDescriptor.MemberDescriptor(">=", "greater_or_equals", "r:1e4e32fc-e42a-4b05-84e5-5f0ea797c86d(ArduinoML.structure)/5006217702052999751", "greater_or_equals");
  private final EnumerationDescriptor.MemberDescriptor myMember__3 = new EnumerationDescriptor.MemberDescriptor("<", "lower", "r:1e4e32fc-e42a-4b05-84e5-5f0ea797c86d(ArduinoML.structure)/5006217702052999755", "lower");
  private final EnumerationDescriptor.MemberDescriptor myMember__4 = new EnumerationDescriptor.MemberDescriptor("<=", "lower_or_equals", "r:1e4e32fc-e42a-4b05-84e5-5f0ea797c86d(ArduinoML.structure)/5006217702052999760", "lower_or_equals");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x4579a879d7243242L, 0x4579a879d7243244L, 0x4579a879d7243243L, 0x4579a879d7243247L, 0x4579a879d724324bL, 0x4579a879d7243250L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember__0, myMember__1, myMember__2, myMember__3, myMember__4);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember__0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "==":
        return myMember__0;
      case ">":
        return myMember__1;
      case ">=":
        return myMember__2;
      case "<":
        return myMember__3;
      case "<=":
        return myMember__4;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
