package ArduinoML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAction = createDescriptorForAction();
  /*package*/ final ConceptDescriptor myConceptActuator = createDescriptorForActuator();
  /*package*/ final ConceptDescriptor myConceptAnalogSensor = createDescriptorForAnalogSensor();
  /*package*/ final ConceptDescriptor myConceptAnalogicalTuple = createDescriptorForAnalogicalTuple();
  /*package*/ final ConceptDescriptor myConceptApp = createDescriptorForApp();
  /*package*/ final ConceptDescriptor myConceptBrick = createDescriptorForBrick();
  /*package*/ final ConceptDescriptor myConceptDigitalSensor = createDescriptorForDigitalSensor();
  /*package*/ final ConceptDescriptor myConceptDigitalTuple = createDescriptorForDigitalTuple();
  /*package*/ final ConceptDescriptor myConceptLcdScreen = createDescriptorForLcdScreen();
  /*package*/ final ConceptDescriptor myConceptSensor = createDescriptorForSensor();
  /*package*/ final ConceptDescriptor myConceptState = createDescriptorForState();
  /*package*/ final ConceptDescriptor myConceptTransition = createDescriptorForTransition();
  /*package*/ final ConceptDescriptor myConceptTuple = createDescriptorForTuple();
  /*package*/ final EnumerationDescriptor myEnumerationOPERATOR = new EnumerationDescriptor_OPERATOR();
  /*package*/ final EnumerationDescriptor myEnumerationSIGNAL = new EnumerationDescriptor_SIGNAL();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAction, myConceptActuator, myConceptAnalogSensor, myConceptAnalogicalTuple, myConceptApp, myConceptBrick, myConceptDigitalSensor, myConceptDigitalTuple, myConceptLcdScreen, myConceptSensor, myConceptState, myConceptTransition, myConceptTuple);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Action:
        return myConceptAction;
      case LanguageConceptSwitch.Actuator:
        return myConceptActuator;
      case LanguageConceptSwitch.AnalogSensor:
        return myConceptAnalogSensor;
      case LanguageConceptSwitch.AnalogicalTuple:
        return myConceptAnalogicalTuple;
      case LanguageConceptSwitch.App:
        return myConceptApp;
      case LanguageConceptSwitch.Brick:
        return myConceptBrick;
      case LanguageConceptSwitch.DigitalSensor:
        return myConceptDigitalSensor;
      case LanguageConceptSwitch.DigitalTuple:
        return myConceptDigitalTuple;
      case LanguageConceptSwitch.LcdScreen:
        return myConceptLcdScreen;
      case LanguageConceptSwitch.Sensor:
        return myConceptSensor;
      case LanguageConceptSwitch.State:
        return myConceptState;
      case LanguageConceptSwitch.Transition:
        return myConceptTransition;
      case LanguageConceptSwitch.Tuple:
        return myConceptTuple;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationOPERATOR, myEnumerationSIGNAL);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Action", 0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x36bafc91071469deL);
    b.class_(false, false, false);
    b.origin("r:1e4e32fc-e42a-4b05-84e5-5f0ea797c86d(ArduinoML.structure)/3943742123535526366");
    b.version(2);
    b.property("signal", 0x36bafc91071469e1L).type(MetaIdFactory.dataTypeId(0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x36bafc91071469e3L)).origin("3943742123535526369").done();
    b.associate("target", 0x36bafc91071469edL).target(0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x36bafc91071469e8L).optional(false).origin("3943742123535526381").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForActuator() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Actuator", 0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x36bafc91071469e8L);
    b.class_(false, false, false);
    b.super_("ArduinoML.structure.Brick", 0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x268865f2b20c7810L);
    b.origin("r:1e4e32fc-e42a-4b05-84e5-5f0ea797c86d(ArduinoML.structure)/3943742123535526376");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAnalogSensor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "AnalogSensor", 0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x411d9e4df106abf7L);
    b.class_(false, false, false);
    b.super_("ArduinoML.structure.Sensor", 0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x268865f2b20c7819L);
    b.origin("r:1e4e32fc-e42a-4b05-84e5-5f0ea797c86d(ArduinoML.structure)/4692080444383341559");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAnalogicalTuple() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "AnalogicalTuple", 0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x59cc86669816610L);
    b.class_(false, false, false);
    b.super_("ArduinoML.structure.Tuple", 0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x4579a879d7243262L);
    b.origin("r:1e4e32fc-e42a-4b05-84e5-5f0ea797c86d(ArduinoML.structure)/404418408738809360");
    b.version(2);
    b.property("value", 0x59cc86669816623L).type(PrimitiveTypeId.INTEGER).origin("404418408738809379").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForApp() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "App", 0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x36bafc91071469f7L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x33d23ee961a0cbf3L);
    b.origin("r:1e4e32fc-e42a-4b05-84e5-5f0ea797c86d(ArduinoML.structure)/3943742123535526391");
    b.version(2);
    b.associate("initial_state", 0x19a0a7798d8fae1L).target(0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x36bafc91071469efL).optional(false).origin("115416249233111777").done();
    b.aggregate("states", 0x36bafc91071469faL).target(0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x36bafc91071469efL).optional(false).ordered(true).multiple(true).origin("3943742123535526394").done();
    b.aggregate("bricks", 0x268865f2b20cc851L).target(0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x268865f2b20c7810L).optional(false).ordered(true).multiple(true).origin("2776581263317583953").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBrick() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Brick", 0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x268865f2b20c7810L);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:1e4e32fc-e42a-4b05-84e5-5f0ea797c86d(ArduinoML.structure)/2776581263317563408");
    b.version(2);
    b.property("pin", 0x268865f2b20c7813L).type(PrimitiveTypeId.INTEGER).origin("2776581263317563411").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDigitalSensor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "DigitalSensor", 0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x411d9e4df106abf6L);
    b.class_(false, false, false);
    b.super_("ArduinoML.structure.Sensor", 0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x268865f2b20c7819L);
    b.origin("r:1e4e32fc-e42a-4b05-84e5-5f0ea797c86d(ArduinoML.structure)/4692080444383341558");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDigitalTuple() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "DigitalTuple", 0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x59cc8666981660fL);
    b.class_(false, false, false);
    b.super_("ArduinoML.structure.Tuple", 0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x4579a879d7243262L);
    b.origin("r:1e4e32fc-e42a-4b05-84e5-5f0ea797c86d(ArduinoML.structure)/404418408738809359");
    b.version(2);
    b.property("value", 0x59cc86669816625L).type(MetaIdFactory.dataTypeId(0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x36bafc91071469e3L)).origin("404418408738809381").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLcdScreen() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "LcdScreen", 0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x5a540d960905d9bdL);
    b.class_(false, false, false);
    b.super_("ArduinoML.structure.Brick", 0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x268865f2b20c7810L);
    b.origin("r:1e4e32fc-e42a-4b05-84e5-5f0ea797c86d(ArduinoML.structure)/6508842299504843197");
    b.version(2);
    b.property("rs", 0x5a540d960905d9c4L).type(PrimitiveTypeId.INTEGER).origin("6508842299504843204").done();
    b.property("rw", 0x5a540d960905d9c6L).type(PrimitiveTypeId.INTEGER).origin("6508842299504843206").done();
    b.property("d4", 0x5a540d960905d9cdL).type(PrimitiveTypeId.INTEGER).origin("6508842299504843213").done();
    b.property("d5", 0x5a540d960905d9d2L).type(PrimitiveTypeId.INTEGER).origin("6508842299504843218").done();
    b.property("d6", 0x5a540d960905d9d8L).type(PrimitiveTypeId.INTEGER).origin("6508842299504843224").done();
    b.property("d7", 0x5a540d960905d9dfL).type(PrimitiveTypeId.INTEGER).origin("6508842299504843231").done();
    b.property("message", 0x5a540d960905d9e7L).type(PrimitiveTypeId.STRING).origin("6508842299504843239").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSensor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Sensor", 0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x268865f2b20c7819L);
    b.class_(false, true, false);
    b.super_("ArduinoML.structure.Brick", 0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x268865f2b20c7810L);
    b.origin("r:1e4e32fc-e42a-4b05-84e5-5f0ea797c86d(ArduinoML.structure)/2776581263317563417");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForState() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "State", 0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x36bafc91071469efL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:1e4e32fc-e42a-4b05-84e5-5f0ea797c86d(ArduinoML.structure)/3943742123535526383");
    b.version(2);
    b.aggregate("actions", 0x36bafc91071469f2L).target(0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x36bafc91071469deL).optional(false).ordered(true).multiple(true).origin("3943742123535526386").done();
    b.aggregate("transitions", 0xa00ce583b2832a2L).target(0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0xa00ce583b28329aL).optional(false).ordered(true).multiple(true).origin("720802818724213410").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTransition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Transition", 0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0xa00ce583b28329aL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x33d23ee961a0cbf3L);
    b.origin("r:1e4e32fc-e42a-4b05-84e5-5f0ea797c86d(ArduinoML.structure)/720802818724213402");
    b.version(2);
    b.associate("next", 0xa00ce583b28329bL).target(0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x36bafc91071469efL).optional(false).origin("720802818724213403").done();
    b.aggregate("tuple", 0x4579a879d7243275L).target(0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x4579a879d7243262L).optional(false).ordered(true).multiple(true).origin("5006217702052999797").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTuple() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Tuple", 0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x4579a879d7243262L);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:1e4e32fc-e42a-4b05-84e5-5f0ea797c86d(ArduinoML.structure)/5006217702052999778");
    b.version(2);
    b.property("operator", 0x4579a879d724326bL).type(MetaIdFactory.dataTypeId(0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x4579a879d7243242L)).origin("5006217702052999787").done();
    b.associate("sensor", 0x4579a879d724326eL).target(0xdc4471fe75cf409bL, 0xbf038bc732728db2L, 0x268865f2b20c7819L).optional(false).origin("5006217702052999790").done();
    return b.create();
  }
}
